# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://parodybit.net
home_url: http://parodybit.net
title: parody bit
subtitle: stream of consciousness
author: Kirk Elifson
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /blog/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: kirk@parodybit.net

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /blog
permalink: /:year/:month/:day/:title/
source: source
destination: public/blog
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir:       # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

default_asides: [asides/github.html]

# Github repositories
github_user: kirkelifson
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: kelifson
twitter_tweet_button: true
